Intelligent angle searcher + StrategyFromPaper2
jotoh98/treasureHunt pull request #110
Opened 2019-12-26 22:10 UTC by Trampeltier

Added 2 Strategies

2019-12-29 09:00 UTC, jotoh98 requested changes
Assuming your code is running, you just have to improve the doc-comments and the readability of your code. Variables named `i` or `k` and huge functions slow down the understanding and due to that the review of your PRs. You also didn't provide any UnitTests, which is bad practice but can be ignored for now. The build of your PR failed because of malformed HTML - I pointed out the exact location.

2019-12-29 09:00 UTC, jotoh98 commented on src/main/java/com/treasure/hunt/strategy/searcher/impl/sfp2/StrategyFromPaper2.java
> + * which for angles beta < 2 * PI has traveling time in O(n ^ (2 - epsilon)).
```suggestion
 * which for angles beta &lt; 2 * PI has traveling time in O(n ^ (2 - epsilon)).
```
We have to format the javadoc comments in proper HTML for the CI javadoc compilation to work.

2019-12-29 09:00 UTC, jotoh98 commented on src/main/java/com/treasure/hunt/strategy/searcher/impl/StrategyFromPaper.java
>          int k = (int) A.distance(B);
```suggestion
        int roundedDistance = (int) A.distance(B);
```
Idk something more descriptive. Refactoring the code (or even just renaming vars) would make it more readable and accelerate the merge and review times a lot.

2019-12-29 09:00 UTC, jotoh98 commented on src/main/java/com/treasure/hunt/strategy/searcher/impl/StrategyFromPaper.java
>          if (k % 2 == 1) //code like in paper
```suggestion
        if (k % 2 == 1)
```
No inline-comments, extract a method and rename it comprehensible.

2019-12-29 09:00 UTC, jotoh98 commented on src/main/java/com/treasure/hunt/strategy/searcher/impl/sfp2/Tile.java
> +    private Coordinate location;
How are the four corner positions represented here? These doc-comments have to be improved.

2019-12-29 09:00 UTC, jotoh98 commented on src/main/java/com/treasure/hunt/strategy/searcher/impl/sfp2/Tile.java
> +    Tile[] subtiles;
Please improve the doc-comments.

2020-01-05 15:08 UTC, 1-alex98 requested changes

2020-01-05 15:08 UTC, axel1200 commented on src/main/java/com/treasure/hunt/strategy/searcher/impl/StrategyFromPaper.java
> +                //System.out.println("a[ "+ i + "] = " + a[i]);
remove comments we have git

2020-01-05 15:08 UTC, axel1200 commented on src/main/java/com/treasure/hunt/strategy/searcher/impl/sfp2/StrategyFromPaper2.java
> +            System.out.println("Index( " + i + ") = "+  index(Angle.toRadians(i)));
No commented out code

2020-01-05 15:08 UTC, axel1200 commented on src/main/java/com/treasure/hunt/strategy/searcher/impl/sfp2/StrategyFromPaper2.java
> +        //System.out.println("maxSteps: " + maxSteps);
...

2020-01-05 15:08 UTC, axel1200 commented on src/main/java/com/treasure/hunt/strategy/searcher/impl/sfp2/StrategyFromPaper2.java
> +                        //System.out.println("Error waiting for hint in Mosaic().");
Handle excption properly

2020-01-05 15:08 UTC, axel1200 commented on src/main/java/com/treasure/hunt/strategy/searcher/impl/sfp2/StrategyFromPaper2.java
> +                    System.out.println("Error waiting in move().");
No system out print lines we have a logger

2020-01-05 15:08 UTC, axel1200 commented on src/main/java/com/treasure/hunt/strategy/searcher/impl/sfp2/StrategyFromPaper2.java
> +                System.out.println("Error waiting in move().");
...

2020-01-05 15:08 UTC, axel1200 commented on src/main/java/com/treasure/hunt/strategy/searcher/impl/sfp2/StrategyFromPaper2.java
> +        //return (int)Math.ceil(0.25*i/(double)k);
...

2020-01-05 17:54 UTC, 1-alex98 submitted a review, later dismissed

2020-01-05 18:02 UTC, 1-alex98 requested changes

2020-01-05 18:02 UTC, axel1200 commented on src/main/java/com/treasure/hunt/strategy/searcher/impl/sfp2/StrategyFromPaper2.java
> +                        //System.out.println("Error waiting for hint in Mosaic().");
...

2020-01-05 18:02 UTC, axel1200 commented on src/main/java/com/treasure/hunt/strategy/searcher/impl/sfp2/StrategyFromPaper2.java
> +        /*The index function
java doc

2020-01-05 18:02 UTC, axel1200 commented on src/main/java/com/treasure/hunt/strategy/searcher/impl/sfp2/StrategyFromPaper2.java
> +        /*The formula from the paper is:
java doc

2020-01-12 20:41 UTC, closed without merging