Strategy from paper
jotoh98/treasureHunt pull request #149
Opened 2020-01-27 13:55 UTC by bsen

Basic strategy from the paper

2020-02-02 20:58 UTC, 1-alex98 requested changes
At least remove al System.outs

2020-02-02 20:58 UTC, axel1200 commented on src/main/java/com/treasure/hunt/strategy/hint/impl/HalfPlaneHint.java
> +    // when the line indicated by anglePointLeft and anglePointRight is not horizontal,
This should be java doc

2020-02-02 20:58 UTC, axel1200 commented on src/main/java/com/treasure/hunt/strategy/searcher/impl/strategyFromPaper/BadHintSubroutine.java
> +    }
This method is way to long split it up

2020-02-02 20:58 UTC, axel1200 commented on src/main/java/com/treasure/hunt/strategy/searcher/impl/strategyFromPaper/BadHintSubroutine.java
> +    static Movement lastHintBadSubroutine(StrategyFromPaper strategy, HalfPlaneHint curHint, HalfPlaneHint lastBadHint,
Why is everything static , maybe make it a singleton or well u can also leave it

2020-02-02 20:58 UTC, axel1200 commented on src/main/java/com/treasure/hunt/strategy/searcher/impl/strategyFromPaper/BadHintSubroutine.java
> +        System.out.println("lastBadHint p1= " + lastBadHint.getCenter() + "lastHint p2= " +
1 Finger

2020-02-02 20:58 UTC, axel1200 commented on src/main/java/com/treasure/hunt/strategy/searcher/impl/strategyFromPaper/BadHintSubroutine.java
> +        System.out.println(" D= (" + D.getX() + ", " + D.getY() + ")");
Ganz viele Finger

2020-02-02 20:58 UTC, axel1200 commented on src/main/java/com/treasure/hunt/strategy/searcher/impl/strategyFromPaper/BadHintSubroutine.java
> +        System.out.println("curHint p1= " + curHint.getCenter() + "curHint p2= " +
Noch mehr Fnger

2020-02-02 20:58 UTC, axel1200 commented on src/main/java/com/treasure/hunt/strategy/searcher/impl/strategyFromPaper/GeometricUtils.java
> +
newline too much

2020-02-02 20:58 UTC, axel1200 commented on src/test/java/com/treasure/hunt/strategy/searcher/impl/StrategyFromPaperTest.java
> +        true_points = new Point[]{createPoint(0.75, -0.5), createPoint(0.75, 1.25)};
Stick to variable naming conventions

2020-02-02 20:58 UTC, axel1200 commented on src/test/java/com/treasure/hunt/strategy/searcher/impl/StrategyFromPaperTest.java
> +        System.out.println();
Finger

2020-02-02 20:58 UTC, axel1200 commented on src/main/java/com/treasure/hunt/strategy/searcher/impl/strategyFromPaper/RoutinesFromPaper.java
> +        { //create a_i on line segment AB
Well whatever this is supposed to be probably extract it into a method

2020-02-02 20:58 UTC, axel1200 commented on src/main/java/com/treasure/hunt/strategy/searcher/impl/strategyFromPaper/RoutinesFromPaper.java
> +        {
Tick the format boxes in the commit message or str+alt+l { should be same lie as loop

2020-02-02 20:58 UTC, axel1200 commented on src/main/java/com/treasure/hunt/strategy/searcher/impl/strategyFromPaper/GeometricUtils.java
> +        double max_x = -Double.MAX_VALUE;
var naming conventions

2020-02-02 20:58 UTC, axel1200 commented on src/main/java/com/treasure/hunt/strategy/searcher/impl/strategyFromPaper/GeometricUtils.java
> +        Coordinate A = null, B = null, C = null, D = null;
What the hack are A B C And D

2020-02-02 20:58 UTC, axel1200 commented on src/main/java/com/treasure/hunt/strategy/searcher/impl/strategyFromPaper/GeometricUtils.java
> +        if (rect.length != 4)
Then lets call it reactangle

2020-02-02 20:58 UTC, axel1200 commented on src/main/java/com/treasure/hunt/strategy/searcher/impl/strategyFromPaper/BadHintSubroutine.java
> +                curHint.getRight());
Abbreviations are bad for your mental health

2020-02-02 20:58 UTC, axel1200 commented on src/main/java/com/treasure/hunt/strategy/searcher/impl/strategyFromPaper/BadHintSubroutine.java
> +            if ((x2_apos == left &&
Maybe a more descriptive name also namingconventions

2020-02-11 14:19 UTC, axel1200 commented
Still not all old comments addressed at least address System.out.println

2020-02-11 20:54 UTC, bsen commented
> Still not all old comments addressed at least address System.out.println

Yes, I'm going to change that

2020-03-02 21:21 UTC, closed without merging