Strategy from paper
jotoh98/treasureHunt pull request #26
Opened 2019-11-12 08:22 UTC by bsen

Beginning the implementation of the strategy from the paper

2019-11-12 08:44 UTC, jotoh98 requested changes
Overall good work, some implementations seem missing or in work in the algorithm implementation. However, there are some real issues with the DRY principle, please don't implement functionalities twice which are already available with JTS.

2019-11-12 08:44 UTC, jotoh98 commented on src/main/java/com/treasure/hunt/strategy/searcher/implementations/StrategyFromPaper.java
> +    private Moves RectangeScan(Point A, Point B, Point C, Point D){
```suggestion
    private Moves rectangleScan(Point A, Point B, Point C, Point D){
```

2019-11-12 08:44 UTC, jotoh98 commented on src/main/java/com/treasure/hunt/utils/JTSUtils.java
> +    }
please see org.locationtech.jts.geom. LineSegment.intersection(). 
Maybe this function already exists.

2019-11-12 08:44 UTC, jotoh98 commented on src/main/java/com/treasure/hunt/utils/JTSUtils.java
> +}
Wrapper for lineIntersection()? Can this also be replaced by the JTS function mentioned above?

2019-11-12 08:44 UTC, jotoh98 commented on src/main/java/com/treasure/hunt/strategy/hint/HalfplaneHint.java
> +
Plase pull latest master, we have committed some code styling preferences to enhance readabilty. Also, search for shortcuts reformatting your code. More than 1 blank line inside of code declaration is disabled by default.

2019-11-17 19:20 UTC, 1-alex98 requested changes

2019-11-17 19:20 UTC, axel1200 commented on src/main/java/com/treasure/hunt/strategy/searcher/movesImplementations/Steps.java
> +public class Steps extends Moves {
Why ?

2019-11-17 19:20 UTC, axel1200 commented on src/main/java/com/treasure/hunt/strategy/searcher/movesImplementations/Steps.java
> +public class Steps extends Moves {
just use Moves class

2019-11-17 19:22 UTC, axel1200 commented
Could u merge master in so u stay up to date

2019-11-17 20:31 UTC, closed without merging