Feature/#46 backtracking
jotoh98/treasureHunt pull request #50
Opened 2019-11-25 15:16 UTC by DorianRec

Fixes #46

2019-11-27 16:52 UTC, jotoh98 submitted a review, later dismissed
tested on RandomAngleHintHider with NaiveAngleSearcher and GameManager - clicking next throws IllegalStateException from GameHistory.java:49

2019-12-01 12:44 UTC, DorianRec commented
> tested on RandomAngleHintHider with NaiveAngleSearcher and GameManager - clicking next throws IllegalStateException from GameHistory.java:49

Fixes this now

2019-12-01 21:08 UTC, 1-alex98 requested changes

2019-12-01 21:08 UTC, 1-alex98 commented on src/main/java/com/treasure/hunt/game/GameEngine.java
> +        System.out.println("" +
use logger

2019-12-01 21:08 UTC, 1-alex98 commented on src/main/java/com/treasure/hunt/game/GameEngine.java
> +        List<GeometryItem<Point>> act = new ArrayList<>();
act is not a well chosen name

2019-12-01 21:08 UTC, axel1200 commented on src/main/java/com/treasure/hunt/view/main/MainFrameController.java
> +        /* TODO:
well then do it

2019-12-01 21:16 UTC, 1-alex98 approved these changes

2019-12-01 21:17 UTC, merged